# Generated by Django 2.0.1 on 2019-05-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ns1', '0002_auto_20190510_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fungus_detail',
            old_name='保藏号',
            new_name='pre_no',
        ),
    ]
