# Generated by Django 2.0.1 on 2019-05-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns1', '0003_auto_20190513_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='ns1_3d_detail',
            name='Reference_url',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
